### ISSUE TITLE
Single window

### ISSUE THREAD

**Issue by MinecrafterLunar** [happymimimix/SSW-Recorder#3]
I think if i write a window generator you can put the ui in it(using C++, incompatible with python)
but it creates a win32 window which can be used as a control panel?

**Comment by happymimimix** [comment]
I think drawing the ui directly onto ssw's windows looks really cool.

**Comment by MinecrafterLunar** [comment]
if ssw stops responding it can be a little...yk?
and ui drawing on ssw makes it hard to change the settings directly
you have to change the marker place which is not what i want...

**Comment by happymimimix** [comment]
> if ssw stops responding it can be a little...yk? and ui drawing on ssw makes it hard to change the settings directly you have to change the marker place which is not what i want...

The software is open sourced, you can implement that yourself. 
Hold down the 'Ctrl' key when opening the app to grab the source code with all sorts of other things that you'll need to compile it. 
I'm currently busy working on other things and is unable to implement this. Sorry.
